name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn build
        ls
      env:
        CI: true
      
    - name: Publish to Github Container registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: AIR-DISCOVER/discover-web
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: latest
